# Generated by Django 4.2.2 on 2023-06-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='quantities',
            field=models.ManyToManyField(through='production.WarehouseQuantity', to='production.rawmaterial'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='warehouses',
            field=models.ManyToManyField(through='production.WarehouseQuantity', to='production.warehouse'),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='production.ProductMaterial', to='production.rawmaterial'),
        ),
    ]
