# Generated by Django 4.2.2 on 2023-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product_quantity_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(related_name='products', through='production.ProductMaterial', to='production.rawmaterial'),
        ),
    ]
